wiki/plugins/attachments/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from wiki.plugins.attachments import views

urlpatterns = [
    url(r'^$',
        views.AttachmentView.as_view(),
        name='attachments_index'),
    url(r'^search/$',
        views.AttachmentSearchView.as_view(),
        name='attachments_search'),
    url(r'^add/(?P<attachment_id>\d+)/$',
        views.AttachmentAddView.as_view(),
        name='attachments_add'),
    url(r'^replace/(?P<attachment_id>\d+)/$',
        views.AttachmentReplaceView.as_view(),
        name='attachments_replace'),
    url(r'^history/(?P<attachment_id>\d+)/$',
        views.AttachmentHistoryView.as_view(),
        name='attachments_history'),
    url(r'^download/(?P<attachment_id>\d+)/$',
        views.AttachmentDownloadView.as_view(),
        name='attachments_download'),
    url(r'^delete/(?P<attachment_id>\d+)/$',
        views.AttachmentDeleteView.as_view(),
        name='attachments_delete'),
    url(r'^download/(?P<attachment_id>\d+)/revision/(?P<revision_id>\d+)/$',
        views.AttachmentDownloadView.as_view(),
        name='attachments_download'),
    url(r'^change/(?P<attachment_id>\d+)/revision/(?P<revision_id>\d+)/$',
        views.AttachmentChangeRevisionView.as_view(),
        name='attachments_revision_change'),
]

wiki/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, url
from wiki.conf import settings
from wiki.core.plugins import registry
from wiki.core.plugins.loader import load_wiki_plugins
from wiki.core.utils import get_class_from_str
from wiki.views import accounts, article, deleted_list


class WikiURLPatterns(object):

    '''
    configurator for wiki urls.

    To customize, you can define your own subclass, either overriding
    the view providers, or overriding the functions that collect
    views.
    '''

    # basic views
    article_view_class = article.ArticleView
    article_create_view_class = article.Create
    article_delete_view_class = article.Delete
    article_deleted_view_class = article.Deleted
    article_dir_view_class = article.Dir
    article_edit_view_class = article.Edit
    article_move_view_class = article.Move
    article_preview_view_class = article.Preview
    article_history_view_class = article.History
    article_settings_view_class = article.Settings
    article_source_view_class = article.Source
    article_plugin_view_class = article.Plugin
    revision_change_view_class = article.ChangeRevisionView
    revision_merge_view = staticmethod(article.merge)

    search_view_class = settings.SEARCH_VIEW
    article_diff_view = staticmethod(article.diff)

    # account views
    signup_view_class = accounts.Signup
    login_view_class = accounts.Login
    logout_view_class = accounts.Logout
    profile_update_view_class = accounts.Update

    # deleted list view
    deleted_list_view_class = deleted_list.DeletedListView

    def get_urls(self):
        urlpatterns = self.get_root_urls()
        urlpatterns += self.get_accounts_urls()
        urlpatterns += self.get_deleted_list_urls()
        urlpatterns += self.get_revision_urls()
        urlpatterns += self.get_article_urls()
        urlpatterns += self.get_plugin_urls()

        # This ALWAYS has to be the last of all the patterns since
        # the paths in theory could wrongly match other targets.
        urlpatterns += self.get_article_path_urls()
        return urlpatterns

    def get_root_urls(self):
        urlpatterns = [
            url(r'^_$',
                # self.article_view_class.as_view(),   modified by wx
                self.article_dir_view_class.as_view(),
                name='root',
                kwargs={'path': ''}),
            url(r'^create-root/$',
                article.CreateRootView.as_view(),
                name='root_create'),
            url(r'^missing-root/$',
                article.MissingRootView.as_view(),
                name='root_missing'),
            url(r'^_search/$',
                get_class_from_str(self.search_view_class).as_view(),
                name='search'),
            url(r'^_revision/diff/(?P<revision_id>\d+)/$',
                self.article_diff_view,
                name='diff'),
        ]
        return urlpatterns

    def get_deleted_list_urls(self):
        urlpatterns = [
            url('^_admin/$',
                self.deleted_list_view_class.as_view(),
                name="deleted_list"),
        ]
        return urlpatterns

    def get_accounts_urls(self):
        if settings.ACCOUNT_HANDLING:
            urlpatterns = [
                url(r'^_accounts/sign-up/$',
                    self.signup_view_class.as_view(),
                    name='signup'),
                url(r'^_accounts/logout/$',
                    self.logout_view_class.as_view(),
                    name='logout'),
                url(r'^_accounts/login/$',
                    self.login_view_class.as_view(),
                    name='login'),
                url(r'^_accounts/settings/$',
                    self.profile_update_view_class.as_view(),
                    name='profile_update'),
            ]
        else:
            urlpatterns = []
        return urlpatterns

    def get_revision_urls(self):
        urlpatterns = [
            # This one doesn't work because it don't know
            # where to redirect after...
            url(
                r'^_revision/change/(?P<article_id>\d+)/(?P<revision_id>\d+)/$',
                self.revision_change_view_class.as_view(),
                name='change_revision'),
            url(r'^_revision/preview/(?P<article_id>\d+)/$',
                self.article_preview_view_class.as_view(),
                name='preview_revision'),
            url(
                r'^_revision/merge/(?P<article_id>\d+)/(?P<revision_id>\d+)/preview/$',
                self.revision_merge_view,
                name='merge_revision_preview',
                kwargs={
                    'preview': True}),
        ]
        return urlpatterns

    def get_article_urls(self):
        urlpatterns = [
            # Paths decided by article_ids
            url(r'^(?P<article_id>\d+)/$',
                self.article_view_class.as_view(),
                name='get'),
            url(r'^(?P<article_id>\d+)/delete/$',
                self.article_delete_view_class.as_view(),
                name='delete'),
            url(r'^(?P<article_id>\d+)/deleted/$',
                self.article_deleted_view_class.as_view(),
                name='deleted'),
            url(r'^(?P<article_id>\d+)/edit/$',
                self.article_edit_view_class.as_view(),
                name='edit'),
            url(r'^(?P<article_id>\d+)/move/$',
                self.article_move_view_class.as_view(),
                name='move'),
            url(r'^(?P<article_id>\d+)/preview/$',
                self.article_preview_view_class.as_view(),
                name='preview'),
            url(r'^(?P<article_id>\d+)/history/$',
                self.article_history_view_class.as_view(),
                name='history'),
            url(r'^(?P<article_id>\d+)/settings/$',
                self.article_settings_view_class.as_view(),
                name='settings'),
            url(r'^(?P<article_id>\d+)/source/$',
                self.article_source_view_class.as_view(),
                name='source'),
            url(
                r'^(?P<article_id>\d+)/revision/change/(?P<revision_id>\d+)/$',
                self.revision_change_view_class.as_view(),
                name='change_revision'),
            url(
                r'^(?P<article_id>\d+)/revision/merge/(?P<revision_id>\d+)/$',
                self.revision_merge_view,
                name='merge_revision'),
            url(r'^(?P<article_id>\d+)/plugin/(?P<slug>\w+)/$',
                self.article_plugin_view_class.as_view(),
                name='plugin'),
        ]
        return urlpatterns

    def get_article_path_urls(self):
        urlpatterns = [
            # Paths decided by URLs
            url(r'^(?P<path>.+/|)_create/$',
                self.article_create_view_class.as_view(),
                name='create'),
            url(r'^(?P<path>.+/|)_delete/$',
                self.article_delete_view_class.as_view(),
                name='delete'),
            url(r'^(?P<path>.+/|)_deleted/$',
                self.article_deleted_view_class.as_view(),
                name='deleted'),
            url(r'^(?P<path>.+/|)_edit/$',
                self.article_edit_view_class.as_view(),
                name='edit'),
            url(r'^(?P<path>.+/|)_move/$',
                self.article_move_view_class.as_view(),
                name='move'),
            url(r'^(?P<path>.+/|)_preview/$',
                self.article_preview_view_class.as_view(),
                name='preview'),
            url(r'^(?P<path>.+/|)_history/$',
                self.article_history_view_class.as_view(),
                name='history'),
            url(r'^(?P<path>.+/|)_dir/$',
                self.article_dir_view_class.as_view(),
                name='dir'),
            url(r'^_dir/$',
                self.article_dir_view_class.as_view(),
                name='start',
                ),
            url(r'^(?P<path>.+/|)_settings/$',
                self.article_settings_view_class.as_view(),
                name='settings'),
            url(r'^(?P<path>.+/|)_source/$',
                self.article_source_view_class.as_view(),
                name='source'),
            url(
                r'^(?P<path>.+/|)_revision/change/(?P<revision_id>\d+)/$',
                self.revision_change_view_class.as_view(),
                name='change_revision'),
            url(
                r'^(?P<path>.+/|)_revision/merge/(?P<revision_id>\d+)/$',
                self.revision_merge_view,
                name='merge_revision'),
            url(r'^(?P<path>.+/|)_plugin/(?P<slug>\w+)/$',
                self.article_plugin_view_class.as_view(),
                name='plugin'),
            # This should always go last!
            url(r'^(?P<path>.+/|)$',
                self.article_view_class.as_view(),
                name='get'),
        ]
        return urlpatterns

    @staticmethod
    def get_plugin_urls():
        urlpatterns = []
        for plugin in list(registry.get_plugins().values()):
            slug = getattr(plugin, 'slug', None)
            if slug:
                article_urlpatterns = plugin.urlpatterns.get('article', [])
                urlpatterns += [
                    url(r'^(?P<article_id>\d+)/plugin/' + slug + '/',
                        include(article_urlpatterns)),
                    url(r'^(?P<path>.+/|)_plugin/' + slug + '/',
                        include(article_urlpatterns)),
                ]
                root_urlpatterns = plugin.urlpatterns.get('root', [])
                urlpatterns += [
                    url(r'^_plugin/' + slug + '/', include(root_urlpatterns)),
                ]
        return urlpatterns


def get_pattern(app_name="wiki", namespace="wiki", url_config_class=None):
    """Every url resolution takes place as "wiki:view_name".
       You should not attempt to have multiple deployments of the wiki in a
       single Django project.

wiki/plugins/globalhistory/models.py
# -*- coding: utf-8 -*-

wiki/plugins/help/models.py
from __future__ import absolute_import

wiki/plugins/links/models.py
# Keep to avoid import errors

wiki/plugins/globalhistory/views.py
from __future__ import absolute_import, unicode_literals

from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from wiki import models
from wiki.core.paginator import WikiPaginator


class GlobalHistory(ListView):

    template_name = 'wiki/plugins/globalhistory/globalhistory.html'
    paginator_class = WikiPaginator
    paginate_by = 30
    model = models.ArticleRevision
    context_object_name = 'revisions'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.only_last = kwargs.get('only_last', 0)
        return super(GlobalHistory, self).dispatch(
            request, *args, **kwargs)

    def get_queryset(self):
        if self.only_last == '1':
            return self.model.objects.can_read(self.request.user) \
                .filter(article__current_revision=F('id')).order_by('-modified')
        else:
            return self.model.objects.can_read(self.request.user).order_by('-modified')

    def get_context_data(self, **kwargs):
        kwargs['only_last'] = self.only_last
        return super(GlobalHistory, self).get_context_data(**kwargs)

wiki/plugins/haystack/views.py
from __future__ import absolute_import, unicode_literals

from haystack.backends import SQ
from haystack.inputs import AutoQuery
from haystack.query import SearchQuerySet
from wiki import models
from wiki.core import permissions
from wiki.views.article import SearchView


class HaystackSearchView(SearchView):

    template_name = 'wiki/plugins/haystack/search.html'

    def get_queryset(self):
        qs = SearchQuerySet().all()
        if self.request.user.is_authenticated():
            if not permissions.can_moderate(
                    models.URLPath.root().article,
                    self.request.user):
                qs = qs.filter(
                    SQ(owner_id=self.request.user.id) |
                    (
                        SQ(group_id__in=self.request.user.groups.values_list('id', flat=True)) &
                        SQ(group_read=True)
                    ) |
                    SQ(other_read=True)
                )
        else:
            qs = qs.exclude(other_read=False)

        qs = qs.filter(content=AutoQuery(self.query))
        qs = qs.load_all()
        return qs

wiki/plugins/help/views.py
# Create your views here.

wiki/plugins/links/views.py
from __future__ import absolute_import, unicode_literals

from django.utils.decorators import method_decorator
from django.views.generic.base import View
from wiki import models
from wiki.core.utils import object_to_json_response
from wiki.decorators import get_article


class QueryUrlPath(View):

    @method_decorator(get_article(can_read=True))
    def dispatch(self, request, article, *args, **kwargs):
        max_num = kwargs.pop('max_num', 20)
        # TODO: Move this import when circularity issue is resolved
        # https://github.com/django-wiki/django-wiki/issues/23
        query = request.GET.get('query', None)

        matches = []

        if query:
            matches = models.URLPath.objects.can_read(
                request.user).active().filter(
                article__current_revision__title__contains=query,
                article__current_revision__deleted=False,
            )
            matches = matches.select_related_common()
            matches = [
                "[{title:s}](wiki:{url:s})".format(
                    title=m.article.current_revision.title,
                    url='/' + m.path.strip("/")
                ) for m in matches[:max_num]
            ]

        return object_to_json_response(matches)

wiki/plugins/notifications/views.py
from __future__ import absolute_import, unicode_literals

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views.generic.edit import FormView

from . import forms, models


class NotificationSettings(FormView):

    template_name = 'wiki/plugins/notifications/settings.html'
    form_class = forms.SettingsFormSet

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(
            NotificationSettings,
            self).dispatch(
            request,
            *args,
            **kwargs)

    def form_valid(self, formset):
        for form in formset:
            settings = form.save()
            messages.info(
                self.request,
                _("You will receive notifications %(interval)s for "
                  "%(articles)d articles") % {
                    'interval': settings.get_interval_display(),
                    'articles': self.get_article_subscriptions(form.instance).count(),
                }
            )
        return redirect('wiki:notification_settings')

    def get_article_subscriptions(self, nyt_settings):
        return models.ArticleSubscription.objects.filter(
            subscription__settings=nyt_settings,
            article__current_revision__deleted=False,
        ).select_related(
            'article',
            'article__current_revision'
        ).distinct()

    def get_form_kwargs(self):
        kwargs = FormView.get_form_kwargs(self)
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = FormView.get_context_data(self, **kwargs)
        if 'form' not in context:
            context['form'] = self.get_form()
        context['formset'] = context['form']
        for form in context['formset']:
            if form.instance:
                setattr(
                    form.instance,
                    'articlesubscriptions',
                    self.get_article_subscriptions(form.instance)
                )
        return context

wiki/plugins/attachments/templates/wiki/plugins/attachments/delete.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n humanize %}


{% block wiki_pagetitle %}{% trans "Delete" %} "{{ attachment.current_revision.get_filename }}"{% endblock %}

{% block wiki_contents_tab %}

{% if attachment.article == article %}
<h2>{% trans "delete" %} "{{ attachment.current_revision.get_filename }}"?</h2>
  <p class="lead">
    {% blocktrans with attachment.original_filename as filename %}
    The file may be referenced on other articles. Deleting it means that they will loose their references to this file. The following articles reference this file:
    {% endblocktrans %}
  </p>
  <ul>
    {% for a in attachment.articles.all %}
      <li style="font-size: 150%;">{{ a.current_revision.title }}</li>
    {% endfor %}
  </ul>
<hr />
<form method="POST" class="form-horizontal" id="attachment_form" enctype="multipart/form-data">
  {% wiki_form form %}
  <div class="form-group form-actions">
    <div class="col-lg-2"></div>
    <div class="col-lg-10">
      <a href="{% url 'wiki:attachments_index' path=urlpath.path article_id=article.id %}" class="btn btn-default">
        <span class="fa fa-arrow-left"></span>
        {% trans "Go back" %}
      </a>
      <button class="btn btn-danger">
        <span class="fa fa-remove"></span>
        {% trans "Delete it!" %}
      </button>
    </div>
  </div>
</form>

{% else %}
  <h2>{% trans "Remove" %} "{{ attachment.current_revision.get_filename }}"?</h2>
  <p class="lead">
    {% blocktrans with attachment.original_filename as filename %}
    You can remove a reference to a file, but it will retain its references on other articles.
    {% endblocktrans %}
  </p>
  <form method="POST" class="form-horizontal" id="attachment_form" enctype="multipart/form-data">
  {% wiki_form form %}
  <div class="form-group form-actions">
    <div class="col-lg-2"></div>
    <div class="col-lg-10">
      <a href="{% url 'wiki:attachments_index' path=urlpath.path article_id=article.id %}" class="btn btn-default">
        <span class="fa fa-arrow-left"></span>
        {% trans "Go back" %}
      </a>
      <button class="btn btn-danger">
        <span class="fa fa-remove"></span>
        {% trans "Remove reference" %}
      </button>
    </div>
  </div>
</form>

{% endif %}

{% endblock %}

wiki/plugins/attachments/templates/wiki/plugins/attachments/history.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n humanize %}


{% block wiki_pagetitle %}{% trans "History of" %} "{{ attachment.current_revision.get_filename }}"{% endblock %}

{% block wiki_contents_tab %}

<h2>{% trans "History of" %} "{{ attachment.current_revision.get_filename }}"</h2>
<table class="table table-striped table-bordered">
  <tr>
    <th>{% trans "Date" %}</th>
    <th>{% trans "User" %}</th>
    <th>{% trans "Description" %}</th>
    <th>{% trans "File" %}</th>
    <th>{% trans "Size" %}</th>
    <th style="text-align: right">{% trans "Action" %}</th>
  </tr>
{% for revision in revisions %}
  <tr>
    <td>
      {{ revision.created }}
      {% if revision.deleted %}<span class="badge badge-important">{% trans "deleted" %}</span>{% endif %}
    </td>
    <td>
      {% include "wiki/includes/revision_info.html" with revision=attachment.current_revision hidedate=1 hidenumber=1 %}
    </td>
    <td>{{ revision.description|default:_("<em>No description</em>")|safe }}</td>
    <td>{{ revision.get_filename }}</td>
    <td>{{ revision.get_size|filesizeformat }}</td>
    <td style="text-align: right">
      <form method="POST" action="{% url 'wiki:attachments_revision_change' path=urlpath.path article_id=article.id attachment_id=attachment.id revision_id=revision.id %}">
        {% csrf_token %}
        <a href="{% url 'wiki:attachments_download' path=urlpath.path article_id=article.id attachment_id=attachment.id revision_id=revision.id %}" class="btn btn-primary">
          <span class="fa fa-download"></span>
          {% trans "Download" %}
        </a>
        {% if revision.attachment.article|can_write:user %}
            <button{% if revision == attachment.current_revision %} disabled="disabled"{% endif %} class="btn btn-default">
              <span class="fa fa-flag"></span>
            {% trans "Use this!" %}
            </button>
        {% endif %}
      </form>
    </td>
  </tr>
{% endfor %}
</table>
<a href="{% url 'wiki:attachments_index' path=urlpath.path article_id=article.id %}"><span class="fa fa-arrow-left"></span> {% trans "Go back" %}</a>

{% endblock %}

wiki/plugins/attachments/templates/wiki/plugins/attachments/index.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n humanize %}


{% block wiki_pagetitle %}{% trans "Attachments" %}: {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}
<div class="row">
  <div class="col-lg-8">
    <p class="lead">{% trans "The following files are available for this article. Copy the markdown tag to directly refer to a file from the article text." %}</p>


    {% for attachment in attachments %}
    <table class="table table-bordered table-striped">
      <tr>
        <th colspan="4">
          <h4 style="margin-top:0;">
            <a href="{% url 'wiki:attachments_download' path=urlpath.path article_id=article.id attachment_id=attachment.id %}">{{ attachment.current_revision.get_filename }}</a>
            <span class="badge">{{ attachment.current_revision.created|naturaltime }}</span>
            {% if attachment.current_revision.deleted %}
            <span class="badge badge-important">{% trans "deleted" %}</span>
            {% endif %}
          </h4>
          {{ attachment.current_revision.description }}
        </th>
      </tr>
      <tr>
        <th style="width: 25%">{% trans "Markdown tag" %}</th>
        <th style="width: 25%">{% trans "Uploaded by" %}</th>
        <th style="width: 25%">{% trans "Size" %}</th>
        <td style="width: 25%; text-align: right; white-space: nowrap;" rowspan="2">
          {% if attachment|can_write:user %}
            {% if not attachment.current_revision.deleted %}
              <a href="{% url 'wiki:attachments_replace' path=urlpath.path article_id=article.id attachment_id=attachment.id %}" class="btn btn-default btn-sm">{% trans "Replace" %}</a>
              {% if attachment.article == article %}
                <a href="{% url 'wiki:attachments_delete' path=urlpath.path article_id=article.id attachment_id=attachment.id %}" class="btn btn-default btn-sm">{% trans "Delete" %}</a>
              {% else %}
                <a href="{% url 'wiki:attachments_delete' path=urlpath.path article_id=article.id attachment_id=attachment.id %}" class="btn btn-default btn-sm">{% trans "Detach" %}</a>
              {% endif %}
            {% else %}
               Deleted
            {% endif %}
          {% endif %}
          <p style="margin-top: 10px; margin-bottom:0;">
          <a href="{% url 'wiki:attachments_history' path=urlpath.path article_id=article.id attachment_id=attachment.id %}">
            <span class="fa fa-clock-o"></span>
            {% trans "File history" %} ({{ attachment.attachmentrevision_set.all.count }} {% trans "revisions" %})
          </a>
          </p>
        </td>
      </tr>
      <tr>
        <td><code>[attachment:{{ attachment.id }}]</code></td>
        <td>
        {% include "wiki/includes/revision_info.html" with revision=attachment.current_revision hidedate=1 hidenumber=1 %}
        </td>
        <td>{{ attachment.current_revision.get_size|filesizeformat }}</td>
      </tr>
    </table>
    {% empty %}

      <p style="margin-bottom: 20px;"><em>{% trans "There are no attachments for this article." %}</em></p>

    {% endfor %}
  </div>
  <div class="col-lg-4" style="min-width: 330px;">
  {% if article|can_write:user and not article|is_locked %}
    <div class="panel-group">
      <div class="panel panel-default">
        <div class="panel-heading">
          <a class="panel-toggle" href="#collapse_upload" data-toggle="collapse">
            <h4 class="panel-title"><span class="fa fa-fw fa-upload"></span> {% trans "Upload new file" %}</h4>
          </a>
        </div>

        <div id="collapse_upload" class="panel-collapse collapse{% if form.errors %} in{% endif %}">
          <div class="panel-body">
            {% if anonymous_disallowed %}
              {% include "wiki/includes/anonymous_blocked.html" %}
            {% else %}
            <form method="POST" class="form-vertical" id="attachment_form" enctype="multipart/form-data">
              {% wiki_form form %}
              <button type="submit" name="save" value="1" class="btn btn-primary">
                {% trans "Upload file" %}
              </button>
            </form>
            {% endif %}
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <a class="panel-toggle" data-toggle="collapse" href="#collapse_add">
            <h4 class="panel-title"><span class="fa fa-fw fa-plus-circle"></span> {% trans "Search and add file" %}</h4>
          </a>
        </div>

        <div id="collapse_add" class="panel-collapse collapse">
          <div class="panel-body">
            <p>{% trans "You can reuse files from other articles. These files are subject to updates on other articles which may or may not be a good thing." %}</p>
            <form method="GET" action="{% url 'wiki:attachments_search' path=urlpath.path article_id=article.id %}" class="wiki-form-block">
              <div class="input-group">
                {{ search_form.query }}
                <span class="input-group-btn">
                  <button class="btn btn-default" type="submit">
                    <span class="fa fa-search"></span>
                  </button>
                </span>
              </div><!-- /input-group -->
            </form>
          </div>
        </div>
      </div>

      {% if article|can_write:user %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <a class="panel-toggle" data-toggle="collapse" href="#collapse_restore">
              <h4 class="panel-title"><span class="fa fa-fw fa-trash"></span> {% trans "Restore attachments" %}</h4>
            </a>
          </div>
          <div id="collapse_restore" class="panel-collapse collapse">
            <div class="panel-body">

            {% for attachment in deleted_attachments %}
            <p>
              {{ attachment.current_revision.get_filename }}
              {% if attachment.current_revision.previous_revision.id %}
              <form method="POST" action="{% url 'wiki:attachments_revision_change' path=urlpath.path article_id=article.id attachment_id=attachment.id revision_id=attachment.current_revision.previous_revision.id %}" style="margin:0; padding:0;">
                {% csrf_token %}
                <button class="btn btn-default">
                  {% trans "Restore" %}
                </button>
              </form>
              {% endif %}
            </p>
            {% empty %}

            <p><em>{% trans "Nothing to restore" %}</em></p>

            {% endfor %}

            </div>
          </div>
        </div>
      {% endif %}


    </div>
  {% else %}

    {% if article|is_locked %}
    <p class="muted">
      <i class="fa fa-lock"></i>
      {% trans "The article is currently locked for editing, and therefore no new attachments can be added." %}
    </p>
    {% endif %}

  {% endif %}
  </div>

</div>

{% endblock %}

wiki/plugins/attachments/templates/wiki/plugins/attachments/search.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n humanize %}


{% block wiki_pagetitle %}{% trans "Add file to" %} "{{ article.current_revision.title }}"{% endblock %}

{% block wiki_contents_tab %}

<h2>{% trans "Add attachment from other article" %}</h2>

<form method="GET" action="{% url 'wiki:attachments_search' path=urlpath.path article_id=article.id %}" class="form-search">
  <div class="input-group">
    {{ search_form.query }}
    <span class="input-group-btn">
      <button class="btn btn-default">
        <span class="fa fa-search"></span>
        {% trans "Search files and articles" %}
      </button>
    </span>
  </div>
</form>

{% if attachments %}
<table class="table table-striped table-bordered">
  <tr>
    <th>{% trans "File" %}</th>
    <th>{% trans "Main article" %}</th>
    <th>{% trans "Date" %}</th>
    <th>{% trans "Uploaded by" %}</th>
    <th>{% trans "Size" %}</th>
    <th style="text-align: right">{% trans "Action" %}</th>
  </tr>
{% for attachment in attachments %}
  <tr>
    <td>
      <h4>{{ attachment.original_filename }}</h4>
      {{ attachment.current_revision.description|default:_("<em>No description</em>")|safe }}
    </td>
    <td>
      <strong>{{ attachment.article.current_revision.title }}</strong>
    </td>
    <td>
      {{ attachment.current_revision.created }}
      {% if attachment.current_revision.deleted %}<span class="badge badge-important">{% trans "deleted" %}</span>{% endif %}
    </td>
    <td>
      {% include "wiki/includes/revision_info.html" with revision=attachment.current_revision hidedate=1 hidenumber=1 %}
    </td>
    <td>{{ attachment.current_revision.file.size|filesizeformat }}</td>
    <td style="text-align: right">
      <form method="POST" action="{% url 'wiki:attachments_add' path=urlpath.path article_id=article.id attachment_id=attachment.id %}">
        {% csrf_token %}
        <a href="{% url 'wiki:attachments_download' path=urlpath.path article_id=article.id attachment_id=attachment.id %}" class="btn btn-default">
          <span class="fa fa-download"></span>
          {% trans "Download" %}
        </a>
        <button class="btn btn-primary">
          <span class="fa fa-plus-circle"></span>
        {% trans "Add to article" %}
        </button>
      </form>
    </td>
  </tr>
{% endfor %}
</table>
{% else %}
  <p><em>{% trans "Your search did not return any results" %}</em></p>
{% endif %}

{% with query as appended_value and "query" as appended_key %}
{% include "wiki/includes/pagination.html" %}
{% endwith %}

<p>
  <a href="{% url 'wiki:attachments_index' path=urlpath.path article_id=article.id %}"><span class="fa fa-arrow-left"></span> {% trans "Go back" %}</a>
</p>

{% endblock %}